name: 'Report Workflow Failure'
description: 'An action to report workflow failure to Tracker Boot and create story based on commit message.'

inputs:
  tracker-boot-api-token:
    description: 'Tracker Boot API Key'
    required: true
  project-id:
    description: 'Project ID'
    required: true
  job-status:
    description: 'Job Status'
    required: true

runs:
  using: 'composite'
  steps:
    - name: set up node
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}/scripts
        npm ci
    - name: notify failed CI
      shell: bash
      env:
        TRACKER_BOOT_URL: 'https://trackerboot.com'
        TRACKER_BOOT_API_TOKEN: ${{ inputs.tracker-boot-api-token }}
        PROJECT_ID: ${{ inputs.project-id }}
      if: ${{ inputs.job-status == 'failure' && github.run_attempt == 1}}
      run: |
        cd ${{ github.action_path }}/scripts
        echo "Pipeline is failed. Report CI failure via Tracker Boot."
        WORKFLOW_URL="${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}"
        COMMIT_URL="${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/commit/${{ github.SHA }}"
        npm run action -- notify-failed-ci $WORKFLOW_URL $COMMIT_URL ${{ github.sha }}
