name: Test Custom Action

on:
  workflow_dispatch:
  push:
    paths:
      - 'action.yml'
      - 'scripts/**'

jobs:
  update-story-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v4
      - name: Run Tracker Boot Action
        uses: ./update-story-status
        with:
          tracker-boot-api-token: ${{ secrets.TRACKER_BOOT_API_TOKEN }}
          project-id: "100000025"
          job-status: ${{ job.status }}
  report-workflow-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v4
      - name: Simulate Job Failure
        run: exit 1
      - name: Run Tracker Boot Action
        uses: ./report-workflow-failure
        if: always()
        with:
          tracker-boot-api-token: ${{ secrets.TRACKER_BOOT_API_TOKEN }}
          project-id: "100000025"
          job-status: ${{ job.status }}